[package]
name = "poc-oci-on-demand"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
tar = "0.4.41"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
flate2 = "1.0.30"
tracing-log = "0.2.0"
oci-distribution = "0.11.0"
tokio = { version = "1", features = ["full"] }
